### ISSUE TITLE
Passo 3: Criação da issue para o professor adicionar nome como colaborador na descrição

### ISSUE THREAD

**Issue by camsgoms** [CamilleGomes/GCMS-Camille-Gomes#1]
[README](https://github.com/CamilleGomes/GCMS-Camille-Gomes/edit/main/README.md)

**Comment by CamilleGomes** [comment]
@CamilleGomes 
• Itens do checklist:
o Instalar Git localmente
o Criar projeto local
o Criar repositório local e realizar commits
o Subir alterações para o repositório remoto
o Fazer alterações no repositório da turma

**Comment by CamilleGomes** [comment]
@ramidedantas 

- [ ]  Instalar Git localmente
- [ ] Criar projeto local
- [ ] Criar repositório local e realizar commits
- [ ] Subir alterações para o repositório remoto
- [ ] Fazer alterações no repositório da turma

**Comment by CamilleGomes** [comment]
[README](https://github.com/CamilleGomes/GCMS-Camille-Gomes/edit/main/README.md)

**Comment by ramidedantas** [comment]
OK, pode fechar.
